/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.una.Client;

/**
 *
 * @author nico
 */
import java.awt.*;
import java.util.ArrayList;

import static java.lang.Integer.parseInt;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
public class NewJFrame extends javax.swing.JFrame {
    String cama="0";
    int hospital=0;
    int operation=-1;
    int stop=0;
    boolean exito=false;
    boolean newOperation=false;
    String listaCama = null;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    String getCama() {
    	return this.cama;
    }    
    int getHospital() {
    	return this.hospital;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desocupar = new javax.swing.JFrame();
        jButton10 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        titulo8 = new javax.swing.JLabel();
        titulo9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Estado = new javax.swing.JFrame();
        jButton11 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        titulo10 = new javax.swing.JLabel();
        titulo11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Estado1 = new javax.swing.JFrame();
        jButton12 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        titulo12 = new javax.swing.JLabel();
        titulo13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        Desocupar.setBackground(new java.awt.Color(255, 255, 255));
        Desocupar.setLocation(new java.awt.Point(500, 200));
        Desocupar.setSize(new java.awt.Dimension(685, 505));
        Desocupar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 113, 145));
        jButton10.setText("OK");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 113, 145), 2));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Desocupar.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 218, 40));

        jComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(215, 215, 215));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clinicas", "Materno", "IPS", "Migone" }));
        jComboBox4.setAlignmentX(6.0F);
        jComboBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 215, 215), 2));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        Desocupar.getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 30));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 215, 215), 2));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Desocupar.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 300, 30));

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 113, 145));
        jLabel13.setText("INTRODUZCA EL COD. DE CAMA");
        Desocupar.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        titulo8.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        titulo8.setForeground(new java.awt.Color(255, 255, 255));
        titulo8.setText("Operacion");
        titulo8.setVerifyInputWhenFocusTarget(false);
        Desocupar.getContentPane().add(titulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 43));

        titulo9.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        titulo9.setForeground(new java.awt.Color(255, 255, 255));
        titulo9.setText("Cama");
        titulo9.setVerifyInputWhenFocusTarget(false);
        Desocupar.getContentPane().add(titulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        jLabel19.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 113, 145));
        jLabel19.setText("SELECCIONE SU HOSPITAL:");
        Desocupar.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/una/Client/bg.png"))); // NOI18N
        jLabel15.setLabelFor(titulo);
        jLabel15.setToolTipText("");
        jLabel15.setInheritsPopupMenu(false);
        Desocupar.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 713, 507));

        Estado.setBackground(new java.awt.Color(255, 255, 255));
        Estado.setSize(new java.awt.Dimension(685, 505));
        Estado.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 113, 145));
        jButton11.setText("OK");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 113, 145), 2));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Estado.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 300, 40));

        jComboBox5.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(215, 215, 215));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clinicas", "Hospital Materno", "IPS","Migone" }));
        jComboBox5.setAlignmentX(6.0F);
        jComboBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 215, 215), 2));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        Estado.getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 300, 30));

        jLabel17.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 113, 145));
        jLabel17.setText("SELECCIONE SU HOSPITAL:");
        Estado.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        titulo10.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        titulo10.setForeground(new java.awt.Color(255, 255, 255));
        titulo10.setText("Ver ");
        titulo10.setVerifyInputWhenFocusTarget(false);
        Estado.getContentPane().add(titulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 43));

        titulo11.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        titulo11.setForeground(new java.awt.Color(255, 255, 255));
        titulo11.setText("Estado");
        titulo11.setVerifyInputWhenFocusTarget(false);
        Estado.getContentPane().add(titulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/una/Client/bg.png"))); // NOI18N
        jLabel18.setLabelFor(titulo);
        jLabel18.setToolTipText("");
        jLabel18.setInheritsPopupMenu(false);
        Estado.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 713, 507));

        Estado1.setBackground(new java.awt.Color(255, 255, 255));
        Estado1.setSize(new java.awt.Dimension(685, 505));
        Estado1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 113, 145));
        jButton12.setText("OK");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 113, 145), 2));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Estado1.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 160, 40));

        jLabel21.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 113, 145));
        jLabel21.setText("CAMAS:");
        Estado1.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        titulo12.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        titulo12.setForeground(new java.awt.Color(255, 255, 255));
        titulo12.setText("Ver ");
        titulo12.setVerifyInputWhenFocusTarget(false);
        Estado1.getContentPane().add(titulo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 43));

        titulo13.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        titulo13.setForeground(new java.awt.Color(255, 255, 255));
        titulo13.setText("Estado");
        titulo13.setVerifyInputWhenFocusTarget(false);
        Estado1.getContentPane().add(titulo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        jLabel16.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel16.setText("cama_xyz");
        Estado1.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/una/Client/bg.png"))); // NOI18N
        jLabel22.setLabelFor(titulo);
        jLabel22.setToolTipText("");
        jLabel22.setInheritsPopupMenu(false);
        Estado1.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 713, 507));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.gray);
        setLocation(new java.awt.Point(500, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 113, 145));
        jLabel2.setText("FACULTAD POLITECNICA - UNA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 113, 145));
        jLabel1.setText("Desarrollado por: ALUMNOS DE LA MATERIA SISTEMAS DISTRIBUIDOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        titulo.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Operaciones");
        titulo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 43));

        titulo2.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setText("en Hospital");
        titulo2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 40));

        jButton1.setBackground(new java.awt.Color(0, 113, 145));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar Cama");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 218, 53));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 113, 145));
        jButton3.setText("Ver Estado");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 113, 145), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 218, 53));

        jButton6.setBackground(new java.awt.Color(0, 113, 145));
        jButton6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Desocupar Cama");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 218, 53));

        jButton7.setBackground(new java.awt.Color(0, 113, 145));
        jButton7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Agregar Cama");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 218, 53));

        jButton8.setBackground(new java.awt.Color(0, 113, 145));
        jButton8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Ocupar Cama");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 218, 53));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/una/Client/bg.png"))); // NOI18N
        jLabel3.setLabelFor(titulo);
        jLabel3.setToolTipText("");
        jLabel3.setInheritsPopupMenu(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 713, 507));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	this.exito=false; 
    	operation=1; 
        titulo8.setText("Eliminar"); 
        Desocupar.setVisible(true);
        newOperation=true;      	
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:    	
    	this.exito=false;
    	operation=2;
        Estado.setVisible(true);        
    	newOperation=true;    	
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    	this.exito=false; 
    	operation=5; 
        titulo8.setText("Desocupar"); 
        Desocupar.setVisible(true);
        newOperation=true;

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    	this.exito=false;
    	operation=0;
        titulo8.setText("Agregar");
        Desocupar.setVisible(true);         
    	newOperation=true;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    	this.exito=false;
    	operation=4;
        titulo8.setText("Ocupar");
        Desocupar.setVisible(true);         
    	newOperation=true;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        cama=(jTextField4.getText());
        hospital=jComboBox4.getSelectedIndex();
        Desocupar.setVisible(false);
        jTextField4.setText("");
        jComboBox4.setSelectedIndex(0);
        this.exito=true;
        newOperation=false;

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    	this.exito=true;
    	hospital=jComboBox5.getSelectedIndex();
    	Estado1.setVisible(true);
    	Estado.setVisible(false);
    	jLabel16.setText(listaCama);
    	
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    	Estado1.setVisible(false);  
        this.exito=true;
        newOperation=false;
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */

   class MyComponent extends JComponent {

  public void paint(Graphics g) {
    Graphics2D g2d = (Graphics2D) g;
    g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
  }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Desocupar;
    private javax.swing.JFrame Estado;
    private javax.swing.JFrame Estado1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo10;
    private javax.swing.JLabel titulo11;
    private javax.swing.JLabel titulo12;
    private javax.swing.JLabel titulo13;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo8;
    private javax.swing.JLabel titulo9;
    // End of variables declaration//GEN-END:variables


    public static void main(String[] args) {
        new NewJFrame().setVisible(true);
    }        

}
